on:
  push:
    branches:
      - "main"
      - "v2"

name: "Main Branch"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml
